[CmdletBinding()]
param(
    [Parameter(Mandatory = $true)]
    [string]$ProjectDir,

    [string]$Extensions = "*.ps1,*.py,*.js,*.ts,*.jsx,*.tsx,*.rb,*.php,*.java,*.go,*.cs,*.swift,*.kt,*.rs",

    [string]$Exclude = "",

    [int]$MinLines = 6,

    [float]$MinSimilarity = 0.7
)

$resolved = Resolve-Path -LiteralPath $ProjectDir -ErrorAction SilentlyContinue
if (-not $resolved) {
    Write-Error "Path not found: $ProjectDir"
    exit 1
}
$ProjectDir = $resolved.Path

# PROTECTION: never modify ~/.claude/.
function Normalize($p) {
    $base = if ($env:USERPROFILE) { $env:USERPROFILE } else { $HOME }
    $expanded = if ($p.StartsWith('~')) { Join-Path $base $p.Substring(1) } else { $p }
    return [System.IO.Path]::GetFullPath($expanded).TrimEnd('\')
}
$claudeRoot = Normalize (Join-Path $env:USERPROFILE '.claude')
$targetPath = Normalize $ProjectDir
if ($targetPath -eq $claudeRoot -or $targetPath.StartsWith("$claudeRoot\")) {
    Write-Error "PROTECTION: ProjectDir is inside $claudeRoot. Aborting."
    exit 1
}

$ErrorActionPreference = "Stop"
$PSDefaultParameterValues['Out-File:Encoding'] = 'utf8'
$OutputEncoding = [System.Text.UTF8Encoding]::new()
[Console]::OutputEncoding = [System.Text.UTF8Encoding]::new()

$extList = $Extensions -split ',' | ForEach-Object { $_.Trim() }
$excludeList = if ($Exclude) { $Exclude -split ',' | ForEach-Object { $_.Trim() } } else { @() }

# Generated file markers
$generatedMarkers = @('@generated', 'auto-generated', 'DO NOT EDIT', 'This file is generated', 'Autogenerated', '<auto-generated>')
$generatedExtPattern = '\.g\.'

$binaryExts = @('.png', '.jpg', '.jpeg', '.gif', '.bmp', '.ico', '.pdf', '.zip', '.tar', '.gz', '.lock', '.sum', '.exe', '.dll', '.so', '.dylib', '.bin', '.obj', '.lib', '.pdb')

function Get-SourceFiles {
    param([string]$Dir)
    $files = @()
    $excluded = @{ generated = 0; binary = 0; tooShort = 0 }
    foreach ($ext in $extList) {
        $found = Get-ChildItem -Path $Dir -Recurse -Filter $ext -File -ErrorAction SilentlyContinue
        foreach ($f in $found) {
            $skip = $false
            foreach ($ex in $excludeList) {
                if ($f.FullName -like "*$ex*") { $skip = $true; break }
            }
            if ($skip) { continue }
            if ($f.FullName -notmatch '\\node_modules\\' -and $f.FullName -notmatch '\\.git\\' -and $f.FullName -notmatch '\\venv\\' -and $f.FullName -notmatch '\\__pycache__\\' -and $f.FullName -notmatch '\\.next\\') {
                $bi = $false
                foreach ($be in $binaryExts) {
                    if ($f.Extension -eq $be) { $bi = $true; break }
                }
                if ($bi) { $excluded.binary++; continue }

                $relPath = $f.FullName.Substring($Dir.Length).TrimStart('\')
                if ($relPath -match $generatedExtPattern) { $excluded.generated++; continue }

                try {
                    $content = Get-Content -LiteralPath $f.FullName -TotalCount 10 -ErrorAction SilentlyContinue
                    $isGen = $false
                    foreach ($marker in $generatedMarkers) {
                        if ($content -match [regex]::Escape($marker)) { $isGen = $true; break }
                    }
                    if ($isGen) { $excluded.generated++; continue }
                } catch { }

                if ($f.Length -lt 50) { $excluded.tooShort++; continue }
                $files += $f
            }
        }
    }
    return @{ files = $files; excluded = $excluded }
}

function Get-Sha256 {
    param([string]$Text)
    $bytes = [System.Text.Encoding]::UTF8.GetBytes($Text)
    $hasher = [System.Security.Cryptography.SHA256]::Create()
    $hashBytes = $hasher.ComputeHash($bytes)
    return ($hashBytes | ForEach-Object { $_.ToString('x2') }) -join ''
}

function Get-FunctionExtent {
    param([string[]]$Lines, [int]$StartIndex)
    $braces = 0
    $end = $Lines.Length - 1
    $found = $false
    for ($i = $StartIndex; $i -le $end; $i++) {
        $line = $Lines[$i]
        $oc = ($line.ToCharArray() | Where-Object { $_ -eq '{' }).Count
        $cc = ($line.ToCharArray() | Where-Object { $_ -eq '}' }).Count
        $braces += $oc - $cc
        if ($braces -gt 0) { $found = $true }
        if ($found -and $braces -le 0) { return $i }
    }
    return -1
}

function Test-FunctionHead {
    param([string]$Line)
    $tl = $Line.TrimStart()
    if ($tl -match '^(public|private|protected|internal)\s') { return $true }
    if ($tl -match '^(static|async|abstract|virtual|override)\s') { return $true }
    if ($tl -match '^(function|def |fn |func |sub |constructor|init)\s') { return $true }
    if ($tl -match '^(class |interface |struct |enum |trait )\s') { return $true }
    if ($tl -match '^(if|for|while|switch|catch|foreach|else|elif)\s') { return $false }
    if ($tl -match '^(\w+\s*\(.*\)\s*{)') { return $true }
    if ($tl -match '^(\w+\s*=\s*(function|async|\(.*\)\s*=>))') { return $true }
    return $false
}

function Get-Tokens {
    param([string]$Text)
    $tokens = @()
    $sq = [char]39
    $bt = [char]96
    $pat = "\b\w+\b|[{}()\[\];,.\-+*/%=<>!&|^~?:@#]|`"[^`"]*`"|$sq[^$sq]*$sq|$bt[^$bt]*$bt|\d+\.?\d*"
    $wordMatches = [regex]::Matches($Text, $pat)
    foreach ($m in $wordMatches) {
        $tokens += $m.Value
    }
    return $tokens
}

function Normalize-Type2 {
    param([string]$Text)
    $sq = [char]39
    $bt = [char]96
    $norm = $Text
    $norm = $norm -replace '"[^"]*"', '<str>'
    $norm = $norm -replace "$sq[^$sq]*$sq", '<str>'
    $norm = $norm -replace "$bt[^$bt]*$bt", '<str>'
    $norm = $norm -replace '\b\d+\.?\d*\b', '<num>'
    $norm = $norm -replace '\b[a-zA-Z_]\w*\b', '<id>'
    $norm = $norm -replace '\s+', ' '
    return $norm.Trim()
}

function Normalize-Whitespace {
    param([string]$Text)
    $norm = $Text -replace '\s+', ' '
    return $norm.Trim()
}

function Compute-Similarity {
    param([string[]]$TokensA, [string[]]$TokensB)
    if ($TokensA.Count -eq 0 -or $TokensB.Count -eq 0) { return 0.0 }

    $shorter = if ($TokensA.Count -le $TokensB.Count) { $TokensA } else { $TokensB }
    $longer = if ($TokensA.Count -gt $TokensB.Count) { $TokensA } else { $TokensB }

    $setA = @{}
    foreach ($t in $shorter) { $setA[$t] = $true }
    $intersect = 0
    $union = $setA.Count
    $seenInB = @{}
    foreach ($t in $longer) {
        if (-not $seenInB.ContainsKey($t)) {
            if ($setA.ContainsKey($t)) { $intersect++ }
            else { $union++ }
            $seenInB[$t] = $true
        }
    }

    return [Math]::Round($intersect / [Math]::Max($union, 1), 4)
}

$fileData = Get-SourceFiles -Dir $ProjectDir
$files = $fileData.files
$excluded = $fileData.excluded

$allBlocks = @()
$blockId = 0

foreach ($file in $files) {
    $relativePath = $file.FullName.Substring($ProjectDir.Length).TrimStart('\')
    try {
        $content = Get-Content -LiteralPath $file.FullName -Raw -ErrorAction SilentlyContinue
        if (-not $content) { continue }
        $lines = $content -split "`n"
        if ($lines.Length -lt $MinLines) { continue }
    } catch {
        continue
    }

    for ($i = 0; $i -lt $lines.Length; $i++) {
        $line = $lines[$i]
        if (Test-FunctionHead -Line $line) {
            $bodyStart = $i
            $endIdx = Get-FunctionExtent -Lines $lines -StartIndex $bodyStart
            if ($endIdx -gt $bodyStart -and ($endIdx -$bodyStart + 1) -ge $MinLines) {
                $blockLines = @()
                for ($j = $bodyStart; $j -le $endIdx -and $j -lt $lines.Length; $j++) {
                    $blockLines += $lines[$j]
                }
                $blockText = $blockLines -join "`n"
                $rawText = $blockLines | ForEach-Object { $_.TrimEnd() } | Where-Object { $_ -ne '' } | ForEach-Object { $_ -replace '^\s+', '' } | ForEach-Object { $_ -replace '\s+', ' ' }
                $rawJoined = $rawText -join "`n"
                $wsNormalized = Normalize-Whitespace -Text $rawJoined
                $t2Normalized = Normalize-Type2 -Text $rawJoined

                if ($wsNormalized.Length -gt 10) {
                    $blockId++
                    $allBlocks += @{
                        id = $blockId
                        file = $relativePath
                        startLine = $bodyStart + 1
                        endLine = $endIdx + 1
                        lines = $endIdx - $bodyStart + 1
                        type1Hash = Get-Sha256 -Text $wsNormalized
                        type2Hash = Get-Sha256 -Text $t2Normalized
                        tokens = Get-Tokens -Text $rawJoined
                        content = $rawJoined.Substring(0, [Math]::Min(200, $rawJoined.Length))
                    }
                }
            }
        }
    }
}

if ($allBlocks.Count -eq 0) {
    $output = @{
        cloneClusters = @()
        stats = @{
            totalFiles = $files.Count
            totalBlocks = 0
            totalClusters = 0
            totalDuplicatedLines = 0
            cloneDensity = 0.0
            byType = @{ type1 = 0; type2 = 0; type3 = 0; type4 = 0 }
            capped = $false
        }
        excluded = @{ generated = $excluded.generated; binary = $excluded.binary; tooShort = $excluded.tooShort }
        summary = "No code blocks found (min $MinLines lines)."
    }
    $json = $output | ConvertTo-Json -Depth 5
    Write-Output $json
    Write-Output "=== Clone Scan Complete ==="
    Write-Output "  Files scanned: $($files.Count)"
    Write-Output "  Blocks extracted: 0"
    Write-Output "  Result: no blocks (min $MinLines lines)"
    exit 0
}

# Type 1: group by type1Hash (whitespace-normalized)
$type1Groups = @{}
foreach ($block in $allBlocks) {
    $h = $block.type1Hash
    if (-not $type1Groups.ContainsKey($h)) { $type1Groups[$h] = @() }
    $type1Groups[$h] += $block
}
$type1Clusters = @()
$blocksInType1 = @{}
foreach ($kv in $type1Groups.GetEnumerator()) {
    if ($kv.Value.Count -ge 2) {
        $cluster = @{
            type = 1
            similarity = 1.0
            blocks = $kv.Value | ForEach-Object { @{ file = $_.file; startLine = $_.startLine; endLine = $_.endLine; hash = $_.type1Hash; content = $_.content } }
            lines = $kv.Value[0].lines
            fingerprint = $kv.Key
        }
        $type1Clusters += $cluster
        foreach ($b in $kv.Value) { $blocksInType1[$b.id] = $true }
    }
}

# Type 2: group by type2Hash (token-normalized), exclude Type 1 blocks
$type2Groups = @{}
foreach ($block in $allBlocks) {
    if ($blocksInType1.ContainsKey($block.id)) { continue }
    $h = $block.type2Hash
    if (-not $type2Groups.ContainsKey($h)) { $type2Groups[$h] = @() }
    $type2Groups[$h] += $block
}
$type2Clusters = @()
$blocksInType2 = @{}
foreach ($kv in $type2Groups.GetEnumerator()) {
    if ($kv.Value.Count -ge 2) {
        $cluster = @{
            type = 2
            similarity = 1.0
            blocks = $kv.Value | ForEach-Object { @{ file = $_.file; startLine = $_.startLine; endLine = $_.endLine; hash = $_.type2Hash; content = $_.content } }
            lines = $kv.Value[0].lines
            fingerprint = $kv.Key
        }
        $type2Clusters += $cluster
        foreach ($b in $kv.Value) { $blocksInType2[$b.id] = $true }
    }
}

# Type 3: pairwise similarity within Type 2 groups
$type3Clusters = @()
$seenType3Pairs = @{}
foreach ($kv in $type2Groups.GetEnumerator()) {
    $group = $kv.Value
    if ($group.Count -lt 2) { continue }
    for ($i = 0; $i -lt $group.Count; $i++) {
        for ($j = $i + 1; $j -lt $group.Count; $j++) {
            $sim = Compute-Similarity -TokensA $group[$i].tokens -TokensB $group[$j].tokens
            if ($sim -ge $MinSimilarity -and $sim -lt 1.0) {
                $pairKey = "$($group[$i].id)-$($group[$j].id)"
                if (-not $seenType3Pairs.ContainsKey($pairKey)) {
                    $type3Clusters += @{
                        type = 3
                        similarity = $sim
                        blocks = @(
                            @{ file = $group[$i].file; startLine = $group[$i].startLine; endLine = $group[$i].endLine; hash = $group[$i].type2Hash; content = $group[$i].content }
                            @{ file = $group[$j].file; startLine = $group[$j].startLine; endLine = $group[$j].endLine; hash = $group[$j].type2Hash; content = $group[$j].content }
                        )
                        lines = [Math]::Max($group[$i].lines, $group[$j].lines)
                        fingerprint = "t3-$($kv.Key)-$($group[$i].id)-$($group[$j].id)"
                    }
                    $seenType3Pairs[$pairKey] = $true
                }
            }
        }
    }
}

# Type 4: file-level signature candidates for LLM
$fileSignatures = @{}
foreach ($block in $allBlocks) {
    $f = $block.file
    if (-not $fileSignatures.ContainsKey($f)) { $fileSignatures[$f] = @() }
    $nameMatches = [regex]::Matches($block.content, '\b(function|def|class|sub|fn|func|constructor)\s+(\w+)')
    foreach ($nm in $nameMatches) {
        $sym = $nm.Groups[2].Value
        if ($sym -and -not ($fileSignatures[$f] -contains $sym)) { $fileSignatures[$f] += $sym }
    }
}

$type4Candidates = @()
$fileNames = $fileSignatures.Keys | Where-Object { $fileSignatures[$_].Count -gt 0 } | Sort-Object
for ($i = 0; $i -lt $fileNames.Count; $i++) {
    for ($j = $i + 1; $j -lt $fileNames.Count; $j++) {
        $fA = $fileNames[$i]
        $fB = $fileNames[$j]
        $symsA = $fileSignatures[$fA]
        $symsB = $fileSignatures[$fB]
        $intersection = ($symsA | Where-Object { $symsB -contains $_ }).Count
        $union = ($symsA + $symsB | Select-Object -Unique).Count
        if ($union -gt 0) {
            $cosSim = [Math]::Round($intersection / $union, 4)
            if ($cosSim -ge 0.3 -and $intersection -ge 2) {
                $type4Candidates += @{
                    type = 4
                    similarity = $cosSim
                    blocks = @(
                        @{ file = $fA; startLine = 1; endLine = 0 }
                        @{ file = $fB; startLine = 1; endLine = 0 }
                    )
                    lines = 0
                    fingerprint = "t4-$fA-$fB"
                }
            }
        }
    }
}

# Cap at 1000 clusters
$allClusters = $type1Clusters + $type2Clusters + $type3Clusters + $type4Candidates
$capped = $false
if ($allClusters.Count -gt 1000) {
    $allClusters = $allClusters | Select-Object -First 1000
    $capped = $true
}

$totalDuplicated = ($allClusters | Where-Object { $_.type -lt 4 } | ForEach-Object { $_.lines * $_.blocks.Count }) | Measure-Object -Sum | Select-Object -ExpandProperty Sum
if (-not $totalDuplicated) { $totalDuplicated = 0 }

$totalLines = ($files | ForEach-Object {
    try { (Get-Content -LiteralPath $_.FullName -Raw -ErrorAction SilentlyContinue) -split "`n" | Measure-Object | Select-Object -ExpandProperty Count } catch { 0 }
}) | Measure-Object -Sum | Select-Object -ExpandProperty Sum
if (-not $totalLines) { $totalLines = 1 }

$output = @{
    cloneClusters = $allClusters
    stats = @{
        totalFiles = $files.Count
        totalBlocks = $allBlocks.Count
        totalClusters = $allClusters.Count
        totalDuplicatedLines = $totalDuplicated
        cloneDensity = [Math]::Round($totalDuplicated / $totalLines, 4)
        byType = @{
            type1 = $type1Clusters.Count
            type2 = $type2Clusters.Count
            type3 = $type3Clusters.Count
            type4 = $type4Candidates.Count
        }
        capped = $capped
    }
    excluded = @{
        generated = $excluded.generated
        binary = $excluded.binary
        tooShort = $excluded.tooShort
    }
    summary = "Found $($allClusters.Count) clone cluster(s): Type1=$($type1Clusters.Count) Type2=$($type2Clusters.Count) Type3=$($type3Clusters.Count) Type4_candidates=$($type4Candidates.Count). Duplicated lines: $totalDuplicated / $totalLines = $([Math]::Round($totalDuplicated / $totalLines * 100, 1))%."
}

$json = $output | ConvertTo-Json -Depth 5
Write-Output $json

Write-Output "=== Clone Scan Complete ==="
Write-Output "  Files scanned: $($files.Count)"
Write-Output "  Blocks extracted: $($allBlocks.Count)"
Write-Output "  Clusters found: $($allClusters.Count) (T1=$($type1Clusters.Count) T2=$($type2Clusters.Count) T3=$($type3Clusters.Count) T4_candidates=$($type4Candidates.Count))"
Write-Output "  Duplicated lines: $totalDuplicated / $totalLines ($([Math]::Round($totalDuplicated / $totalLines * 100, 1))%)"
if ($capped) { Write-Output "  Note: capped at 1000 clusters" }
Write-Output "  Excluded: $($excluded.generated) generated, $($excluded.binary) binary, $($excluded.tooShort) too short"
Write-Output ""
Write-Output "  Next step: run LLM analysis via SKILL.md steps"
