[CmdletBinding()]
param(
    [Parameter(Mandatory = $true)]
    [string]$ProjectDir,

    [string]$Extensions = "*.ps1,*.py,*.js,*.ts,*.jsx,*.tsx,*.rb,*.php,*.java,*.go,*.cs,*.swift,*.kt,*.rs",

    [string]$Exclude = "",

    [int]$MinContext = 3
)

$resolved = Resolve-Path -LiteralPath $ProjectDir -ErrorAction SilentlyContinue
if (-not $resolved) {
    Write-Error "Path not found: $ProjectDir"
    exit 1
}
$ProjectDir = $resolved.Path

# PROTECTION: never modify ~/.claude/.
function Normalize($p) {
    $base = if ($env:USERPROFILE) { $env:USERPROFILE } else { $HOME }
    $expanded = if ($p.StartsWith('~')) { Join-Path $base $p.Substring(1) } else { $p }
    return [System.IO.Path]::GetFullPath($expanded).TrimEnd('\')
}
$claudeRoot = Normalize (Join-Path $env:USERPROFILE '.claude')
$targetPath = Normalize $ProjectDir
if ($targetPath -eq $claudeRoot -or $targetPath.StartsWith("$claudeRoot\")) {
    Write-Error "PROTECTION: ProjectDir is inside $claudeRoot. Aborting."
    exit 1
}

$ErrorActionPreference = "Stop"
$PSDefaultParameterValues['Out-File:Encoding'] = 'utf8'
$OutputEncoding = [System.Text.UTF8Encoding]::new()
[Console]::OutputEncoding = [System.Text.UTF8Encoding]::new()

$extList = $Extensions -split ',' | ForEach-Object { $_.Trim() }
$excludeList = if ($Exclude) { $Exclude -split ',' | ForEach-Object { $_.Trim() } } else { @() }

$generatedMarkers = @('@generated', 'auto-generated', 'DO NOT EDIT', 'This file is generated', 'Autogenerated', '<auto-generated>')
$generatedExtPattern = '\.g\.'
$binaryExts = @('.png', '.jpg', '.jpeg', '.gif', '.bmp', '.ico', '.pdf', '.zip', '.tar', '.gz', '.lock', '.sum', '.exe', '.dll', '.so', '.dylib', '.bin', '.obj', '.lib', '.pdb')

$errorProneOps = @('open', 'read', 'write', 'connect', 'send', 'recv', 'parse', 'eval', 'deserialize', 'execute', 'query', 'delete', 'remove', 'unlink', 'mkdir', 'rename', 'chmod', 'chown', 'kill', 'signal', 'lock', 'unlock')

$resourceOps = @('new File', 'fopen', 'open(', 'connect(', 'lock(', 'acquire(', 'BeginTransaction', 'getConnection', 'createStatement', 'FileStream', 'StreamReader', 'StreamWriter', 'SqlConnection', 'File.Open')

$ignoredReturnOps = @('try', 'get', 'fetch', 'query', 'delete', 'remove', 'save', 'write')

function Get-SourceFiles {
    param([string]$Dir)
    $files = @()
    foreach ($ext in $extList) {
        $found = Get-ChildItem -Path $Dir -Recurse -Filter $ext -File -ErrorAction SilentlyContinue
        foreach ($f in $found) {
            $skip = $false
            foreach ($ex in $excludeList) {
                if ($f.FullName -like "*$ex*") { $skip = $true; break }
            }
            if ($skip) { continue }
            if ($f.FullName -notmatch '\\node_modules\\' -and $f.FullName -notmatch '\\.git\\' -and $f.FullName -notmatch '\\venv\\' -and $f.FullName -notmatch '\\__pycache__\\' -and $f.FullName -notmatch '\\.next\\' -and $f.FullName -notmatch '\\coverage\\') {
                $bi = $false
                foreach ($be in $binaryExts) {
                    if ($f.Extension -eq $be) { $bi = $true; break }
                }
                if ($bi) { continue }

                $relPath = $f.FullName.Substring($Dir.Length).TrimStart('\')
                if ($relPath -match $generatedExtPattern) { continue }
                try {
                    $head = Get-Content -LiteralPath $f.FullName -TotalCount 10 -ErrorAction SilentlyContinue
                    $isGen = $false
                    foreach ($marker in $generatedMarkers) {
                        if ($head -match [regex]::Escape($marker)) { $isGen = $true; break }
                    }
                    if ($isGen) { continue }
                } catch { }

                if ($f.Length -lt 10) { continue }
                $files += @{ file = $f; relPath = $relPath }
            }
        }
    }
    return $files
}

function Get-Context {
    param([string[]]$Lines, [int]$LineIndex)
    $start = [Math]::Max(0, $LineIndex - $MinContext)
    $end = [Math]::Min($Lines.Length - 1, $LineIndex + $MinContext)
    $ctx = @()
    for ($i = $start; $i -le $end; $i++) {
        $ctx += $Lines[$i]
    }
    return ($ctx -join "`n")
}

function New-Finding {
    param([int]$Id, [string]$Pattern, [string]$Severity, [string]$File, [int]$Line, [string]$Evidence, [string]$Context, [string]$Suggestion)
    return @{
        id = $Id
        pattern = $Pattern
        severity = $Severity
        file = $File
        line = $Line
        evidence = $Evidence.Substring(0, [Math]::Min(200, $Evidence.Length))
        context = $Context.Substring(0, [Math]::Min(500, $Context.Length))
        suggestion = $Suggestion
    }
}

$fileData = Get-SourceFiles -Dir $ProjectDir
$findings = @()
$findingId = 0

foreach ($entry in $fileData) {
    $file = $entry.file
    $relativePath = $entry.relPath
    try {
        $content = Get-Content -LiteralPath $file.FullName -Raw -ErrorAction SilentlyContinue
        if (-not $content) { continue }
        if ($content.Length -gt 10000 -and ($content -split "`n").Length -lt 3) {
            Write-Output "  Warning: Skipping minified file $relativePath"
            continue
        }
        $lines = $content -split "`n"
    } catch {
        continue
    }

    # Detect file-level patterns
    $ext = [System.IO.Path]::GetExtension($file.FullName).ToLower()

    # Pattern 1: Swallowed exceptions (empty catch blocks)
    $swallowedPatterns = @(
        '(catch\s*\([^)]*\)\s*\{\s*\})',
        '(catch\s*\{\s*\})',
        '(except\s+\w+\s*(as\s+\w+)?\s*:\s*(pass|\.{3}))',
        '(rescue\s+(=>\s*\w+)?\s*;\s*end)',
        '(catch\s*\{[^}]*//[^}]*\})'
    )
    foreach ($sp in $swallowedPatterns) {
        $matches = [regex]::Matches($content, $sp, [System.Text.RegularExpressions.RegexOptions]::Multiline)
        foreach ($m in $matches) {
            $lineNum = ($content.Substring(0, $m.Index) -split "`n").Length
            $lineIndex = $lineNum - 1
            # Check if it's truly empty (no statements other than comments/whitespace)
            $blockBody = $m.Value -replace 'catch\s*\([^)]*\)\s*\{', '' -replace 'catch\s*\{', '' -replace '\}', ''
            $blockBody = $blockBody.Trim()
            if ($blockBody -eq '' -or $blockBody -match '^\s*(//.*|/\*.*\*/|\#.*)?$') {
                $findingId++
                $ctx = Get-Context -Lines $lines -LineIndex $lineIndex
                $findings += New-Finding -Id $findingId -Pattern 'swallowed-exception' -Severity 'high' -File $relativePath -Line $lineNum -Evidence $m.Value -Context $ctx -Suggestion 'Log the exception with context or re-throw as a domain-specific exception'
            }
        }
    }

    # Pattern 2: Generic catch
    $genericPatterns = @(
        '(catch\s*\(\s*Exception\s+)',
        '(catch\s*\(\s*Error\s+)',
        '(except\s+(Exception|BaseException)\s*)',
        '(rescue\s+Exception\s*(=>|\s))',
        '(catch\s*\{)',
        '(except\s*:)'
    )
    foreach ($gp in $genericPatterns) {
        $matches = [regex]::Matches($content, $gp, [System.Text.RegularExpressions.RegexOptions]::Multiline)
        foreach ($m in $matches) {
            $lineNum = ($content.Substring(0, $m.Index) -split "`n").Length
            $lineIndex = $lineNum - 1
            # Skip bare catch { } if it's already flagged as swallowed
            $alreadySwallowed = $false
            foreach ($f in $findings) {
                if ($f.file -eq $relativePath -and [Math]::Abs($f.line - $lineNum) -le 1 -and $f.pattern -eq 'swallowed-exception') {
                    $alreadySwallowed = $true; break
                }
            }
            if ($alreadySwallowed) { continue }
            $findingId++
            $ctx = Get-Context -Lines $lines -LineIndex $lineIndex
            $findings += New-Finding -Id $findingId -Pattern 'generic-catch' -Severity 'high' -File $relativePath -Line $lineNum -Evidence $m.Value -Context $ctx -Suggestion 'Catch specific exception types instead of the base Exception class'
        }
    }

    # Pattern 3: Missing error handling on error-prone ops (heuristic: no try in nearby lines)
    if ($ext -in '.ps1', '.py', '.js', '.ts', '.jsx', '.tsx', '.rb', '.java', '.go', '.cs') {
        if ($content -match '\btry\b' -or $content -match '\bTry\b') {
            foreach ($op in $errorProneOps) {
                $opPattern = "(?i)\b$op\s*\("
                $opMatches = [regex]::Matches($content, $opPattern)
                foreach ($om in $opMatches) {
                    $lineNum = ($content.Substring(0, $om.Index) -split "`n").Length
                    $lineIndex = $lineNum - 1
                    $checkLine = $lines[$lineIndex]
                    if ($checkLine -match '^\s*try\s*\{') { continue }

                    # Fast heuristic: check if any try keyword appears in the same function scope
                    # (within 30 lines above, with matching brace depth heuristic)
                    $nearbyTry = $false
                    $startJ = [Math]::Max(0, $lineIndex - 30)
                    for ($j = $startJ; $j -lt $lineIndex; $j++) {
                        if ($lines[$j] -match '\btry\b') {
                            $nearbyTry = $true
                            break
                        }
                    }

                    if (-not $nearbyTry) {
                        # Also skip .NET using() and Python with statements
                        if ($checkLine -match '\busing\s*\(' -or $checkLine -match '\bwith\s+\w+\s*=.*:') { continue }
                        $findingId++
                        $ctx = Get-Context -Lines $lines -LineIndex $lineIndex
                        $findings += New-Finding -Id $findingId -Pattern 'missing-error-handling' -Severity 'medium' -File $relativePath -Line $lineNum -Evidence $checkLine.Trim() -Context $ctx -Suggestion "Wrap the call to $op() in a try/catch block"
                    }
                }
            }
        }
    }

    # Pattern 4: Missing finally
    if ($ext -in '.cs', '.java', '.js', '.ts', '.ps1', '.py') {
        $tryMatches = [regex]::Matches($content, '\btry\b')
        $finallyMatches = [regex]::Matches($content, '\bfinally\b|\bensure\b')
        if ($tryMatches.Count -gt 0 -and $finallyMatches.Count -eq 0) {
            # Check for resource acquisition without finally
            foreach ($rop in $resourceOps) {
                $ropPattern = [regex]::Escape($rop)
                $ropMatches = [regex]::Matches($content, $ropPattern)
                foreach ($rm in $ropMatches) {
                    $lineNum = ($content.Substring(0, $rm.Index) -split "`n").Length
                    $lineIndex = $lineNum - 1
                    # Check if it's in a using/with block
                    $surrounding = ""
                    for ($j = [Math]::Max(0, $lineIndex - 10); $j -le $lineIndex; $j++) {
                        $surrounding += $lines[$j] + " "
                    }
                    if ($surrounding -match '\busing\s*\(' -or $surrounding -match '\bwith\s+\w+\s*=' -or $surrounding -match '\busing\s+\w+\s*=') {
                        continue
                    }
                    $findingId++
                    $ctx = Get-Context -Lines $lines -LineIndex $lineIndex
                    $findings += New-Finding -Id $findingId -Pattern 'missing-finally' -Severity 'medium' -File $relativePath -Line $lineNum -Evidence $lines[$lineIndex].Trim() -Context $ctx -Suggestion 'Add a finally/ensure block to clean up the resource'
                }
            }
        }
    }

    # Pattern 6: Logging without context in catch blocks
    $catchBlocks = [regex]::Matches($content, '(catch\s*\([^)]*\)\s*\{[^}]*\}|except\s+\w+\s*(as\s+\w+)?\s*:\s*[^#]*)')
    foreach ($cb in $catchBlocks) {
        $blockText = $cb.Value
        if ($blockText -match '(log|Log|logger|Logger|console\.error|Console\.WriteLine|Write-Error|print|trace|logging)') {
            # Check if the log statement includes any dynamic data
            $logLine = ""
            $logMatches = [regex]::Matches($blockText, '(?i)(log|console\.error|Console\.WriteLine|Write-Error|print|trace|logging|logger)\s*\([^)]*\)')
            foreach ($lm in $logMatches) {
                $logLine = $lm.Value
                $hasContext = $logLine -match '\$' -or $logLine -match '\{' -or $logLine -match '\+' -or $logLine -match 'f[''"]' -or $logLine -match '\.format' -or $logLine -match '%s' -or $logLine -match '%d'
                if (-not $hasContext) {
                    $lineNum = ($content.Substring(0, $cb.Index) -split "`n").Length
                    $lineIndex = $lineNum - 1
                    $findingId++
                    $ctx = Get-Context -Lines $lines -LineIndex $lineIndex
                    $findings += New-Finding -Id $findingId -Pattern 'logging-without-context' -Severity 'low' -File $relativePath -Line $lineNum -Evidence $logLine -Context $ctx -Suggestion 'Include relevant state (parameters, IDs) in the log message'
                }
            }
        }
    }

    # Pattern 8: Exception type abuse
    $abusePatterns = @(
        '(throw\s+new\s+Exception\s*\()',
        '(throw\s+new\s+Error\s*\()',
        '(raise\s+Exception\s*\()',
        '(throw\s+"[^"]*")',
        "(throw\s+'[^']*')"
    )
    foreach ($ap in $abusePatterns) {
        $matches = [regex]::Matches($content, $ap)
        foreach ($m in $matches) {
            $lineNum = ($content.Substring(0, $m.Index) -split "`n").Length
            $lineIndex = $lineNum - 1
            # Skip if it's a custom exception subclass
            $classContext = ""
            for ($j = [Math]::Max(0, $lineIndex - 5); $j -le $lineIndex; $j++) {
                $classContext += $lines[$j] + " "
            }
            if ($classContext -match 'class\s+\w+Exception' -or $classContext -match 'class\s+\w+Error' -or $classContext -match 'custom exception') {
                continue
            }
            $findingId++
            $ctx = Get-Context -Lines $lines -LineIndex $lineIndex
            $findings += New-Finding -Id $findingId -Pattern 'exception-type-abuse' -Severity 'low' -File $relativePath -Line $lineNum -Evidence $m.Value -Context $ctx -Suggestion 'Throw a specific exception type (e.g. ArgumentNullException, DomainException)'
        }
    }
}

# Pattern 5: Error handling inconsistency (cross-file, simplified heuristic)
# For each error-prone op, count files where it appears with and without try in nearby context
$opFileMap = @{}
foreach ($entry in $fileData) {
    $file = $entry.file
    $relativePath = $entry.relPath
    try {
        $content = Get-Content -LiteralPath $file.FullName -Raw -ErrorAction SilentlyContinue
        if (-not $content) { continue }
        $flines = $content -split "`n"
    } catch { continue }

    $fileHasTry = $content -match '\btry\b'

    foreach ($op in $errorProneOps) {
        $opPattern = "(?i)\b$op\s*\("
        $matches = [regex]::Matches($content, $opPattern)
        if ($matches.Count -gt 0) {
            if (-not $opFileMap.ContainsKey($op)) { $opFileMap[$op] = @{ filesWithTry = @{}; filesWithoutTry = @{} } }
            if ($fileHasTry) {
                $opFileMap[$op].filesWithTry[$relativePath] = $matches[0].Index
            } else {
                $opFileMap[$op].filesWithoutTry[$relativePath] = $matches[0].Index
            }
        }
    }
}

foreach ($op in $opFileMap.Keys) {
    $info = $opFileMap[$op]
    $wFiles = $info.filesWithTry.Keys.Count
    $unwFiles = $info.filesWithoutTry.Keys.Count
    if ($wFiles -gt 0 -and $unwFiles -gt 0) {
        # Flag one representative file from the unprotected side
        $exampleFile = ($info.filesWithoutTry.Keys | Select-Object -First 1)
        $matchIndex = $info.filesWithoutTry[$exampleFile]
        $matchLineNum = 1
        try {
            $exampleContent = Get-Content -LiteralPath (Join-Path $ProjectDir $exampleFile) -Raw -ErrorAction SilentlyContinue
            if ($exampleContent) { $matchLineNum = ($exampleContent.Substring(0, $matchIndex) -split "`n").Length }
        } catch { }
        $findingId++
        $findings += New-Finding -Id $findingId -Pattern 'error-handling-inconsistency' -Severity 'medium' -File $exampleFile -Line $matchLineNum -Evidence "$op() call" -Context "Operation $op() appears in $wFiles file(s) WITH try/catch and $unwFiles file(s) WITHOUT." -Suggestion "Standardize error handling for $op() across all call sites"
    }
}

# Cap at 200
$capped = $false
if ($findings.Count -gt 200) {
    $findings = $findings | Select-Object -First 200
    $capped = $true
}

# Count stats
$sevCounts = @{ high = 0; medium = 0; low = 0 }
$patCounts = @{}
foreach ($f in $findings) {
    $s = $f.severity
    if ($sevCounts.ContainsKey($s)) { $sevCounts[$s]++ }
    $p = $f.pattern
    if (-not $patCounts.ContainsKey($p)) { $patCounts[$p] = 0 }
    $patCounts[$p]++
}
$total = $findings.Count

$output = @{
    findings = $findings
    counts = @{
        total = $total
        bySeverity = $sevCounts
        byPattern = $patCounts
    }
    capped = $capped
    summary = "Found $total error-handling issue(s): $($sevCounts.high) high, $($sevCounts.medium) medium, $($sevCounts.low) low severity."
}

$json = $output | ConvertTo-Json -Depth 5
Write-Output $json

Write-Output "=== Error Handling Scan Complete ==="
Write-Output "  Files scanned: $($fileData.Count)"
Write-Output "  Findings: $total (high: $($sevCounts.high), medium: $($sevCounts.medium), low: $($sevCounts.low))"
Write-Output "  By pattern:"
foreach ($p in $patCounts.GetEnumerator() | Sort-Object Name) {
    Write-Output "    $($p.Key): $($p.Value)"
}
if ($capped) { Write-Output "  Note: capped at 200 findings" }
Write-Output ""
Write-Output "  Next step: run LLM analysis via SKILL.md steps"
